/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package sonar.sample;

import java.util.Arrays;
import java.util.HashSet;
import java.util.Objects;
import java.util.Set;

public class App {
    public String getGreeting() {

        Set<String> names = new HashSet<>();
        Set<String> names2 = new HashSet<>();

        return Arrays.asList("John", "Joe", "john").stream()
                .map(name -> name.toLowerCase())
                .map(name -> {
                    if (!names.add(name)) {
                        return name;
                    }
                    return null;
                })
                .filter(Objects::nonNull)
                .findAny().orElse("no-one");
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());
    }
}
